// File generated by FlutterFire CLI & refactored for environment variables.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps loaded dynamically from .env.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static String _env(String key, String fallback) {
    try {
      return dotenv.env[key] ?? fallback;
    } catch (_) {
      return fallback;
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
        apiKey: _env(
            'FIREBASE_WEB_API_KEY', 'AIzaSyA4f0bQIt7Ex3-nZ_dtwA9LzcRgpx4il1M'),
        appId: _env(
            'FIREBASE_WEB_APP_ID', '1:586525703658:web:4362c0eb230a857b96c693'),
        messagingSenderId: _env('FIREBASE_MESSAGING_SENDER_ID', '586525703658'),
        projectId: _env('FIREBASE_PROJECT_ID', 'gezayo-2179c'),
        authDomain:
            _env('FIREBASE_WEB_AUTH_DOMAIN', 'gezayo-2179c.firebaseapp.com'),
        storageBucket:
            _env('FIREBASE_STORAGE_BUCKET', 'gezayo-2179c.firebasestorage.app'),
      );

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: _env('FIREBASE_ANDROID_API_KEY',
            'AIzaSyDbyNh7NF0XTcpwrsF6YKtAYZq_l7pQ2NE'),
        appId: _env('FIREBASE_ANDROID_APP_ID',
            '1:586525703658:android:34689bce1e46f23596c693'),
        messagingSenderId: _env('FIREBASE_MESSAGING_SENDER_ID', '586525703658'),
        projectId: _env('FIREBASE_PROJECT_ID', 'gezayo-2179c'),
        storageBucket:
            _env('FIREBASE_STORAGE_BUCKET', 'gezayo-2179c.firebasestorage.app'),
      );

  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: _env(
            'FIREBASE_IOS_API_KEY', 'AIzaSyCAY1JFJMDR0ib9XQ922myhwIf3GucujCY'),
        appId: _env(
            'FIREBASE_IOS_APP_ID', '1:586525703658:ios:e5af38feb988a0b396c693'),
        messagingSenderId: _env('FIREBASE_MESSAGING_SENDER_ID', '586525703658'),
        projectId: _env('FIREBASE_PROJECT_ID', 'gezayo-2179c'),
        storageBucket:
            _env('FIREBASE_STORAGE_BUCKET', 'gezayo-2179c.firebasestorage.app'),
        iosBundleId: _env('FIREBASE_IOS_BUNDLE_ID', 'com.example.gezayoApp'),
      );
}
